---
- name: Install Java and set up Minecraft server
  hosts: minecraft
  become: yes
  gather_facts: no

  tasks:
    - name: Install Java
      yum: 
        name: java-25-amazon-corretto-headless
    
    - name: Make user and directories
      user:
        name: minecraft
      file:
        path: /opt/minecraft
        state: directory
        owner: minecraft
        group: minecraft
      file:
        path: /opt/minecraft/server
        state: directory
        owner: minecraft
        group: minecraft

    - name: Get the Minecraft server files
      get_url:
        url: https://piston-data.mojang.com/v1/objects/97ccd4c0ed3f81bbb7bfacddd1090b0c56f9bc51/server.jar
        dest: /opt/minecraft/server/server.jar
        owner: minecraft
        group: minecraft
      copy:
        dest: /opt/minecraft/server/eula.txt
        content: "eula=true\n"

    - name: Set up systemctl to automatically start the Minecraft service.
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server on start up
          Wants=network-online.target
          
          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft/server
          ExecStart=/usr/bin/java -Xmx1300M -Xms1300M -jar server.jar nogui
          Restart=on-failure
          RestartSec=10
          KillSignal=SIGINT
          TimeoutStopSec=60
          StandardInput=null
          
          [Install]
          WantedBy=multi-user.target
        systemd:
          dameon_reload: true
        systemd:
          name: minecraft
          enabled: true
          state: started