---
- name: Manage inventory
  hosts: localhost
  connection: local
  gather_facts:no

  tasks:
    - name: Retrieve launched instance
      community.aws.ec2_instance_info:
        filters:
          "tag:Name": "Auto Minecraft Server"
          instance-state-name: running
      register: ec2

    - name: Put instance in inventory
      add_host:
        name: minecraft
        groups: minecraft
        ansible_host: "{{ ec2.instances[0].public_ip_address }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: auto-minecraft-key.pem

- name: Install Java and set up Minecraft server
  hosts: minecraft
  become: yes
  gather_facts: no

  tasks:
    - name: Install Java
      yum: 
        name: java-25-amazon-corretto-headless
    
    - name: Make user
      user:
        name: minecraft
    
    - name: Make minecraft directory
      file:
        path: /opt/minecraft
        state: directory
        owner: minecraft
        group: minecraft

    - name: Make server directory
      file:
        path: /opt/minecraft/server
        state: directory
        owner: minecraft
        group: minecraft

    - name: Get the Minecraft server files
      get_url:
        url: https://piston-data.mojang.com/v1/objects/97ccd4c0ed3f81bbb7bfacddd1090b0c56f9bc51/server.jar
        dest: /opt/minecraft/server/server.jar
        owner: minecraft
        group: minecraft

    - name: Accept EULA
      copy:
        dest: /opt/minecraft/server/eula.txt
        content: "eula=true\n"

    - name: Set up systemctl to automatically start the Minecraft service.
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server on start up
          Wants=network-online.target
          
          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft/server
          ExecStart=/usr/bin/java -Xmx1300M -Xms1300M -jar server.jar nogui
          Restart=on-failure
          RestartSec=10
          KillSignal=SIGINT
          TimeoutStopSec=60
          StandardInput=null
          
          [Install]
          WantedBy=multi-user.target
    
    - name: Reload systemd
      systemd:
        dameon_reload: true

    - name: Enable minecraft service
      systemd:
        name: minecraft
        enabled: true
        state: started